name: appec
channels:
  - conda-forge
dependencies:
  - python=3.11.3
  - numpy=2.0.2
  - pandas=2.2.2
  - scikit-learn=1.6.1
  - statsmodels=0.14.5
  - matplotlib=3.10.0
  - linearmodels=6.0.0
  - flake8=7.0.0
