name: Assignment Builds

on:
  push:
    branches:
      - "assignment/a0*"

jobs:
  # Assignment 1: t-statistic
  a01:
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'assignment/a01-')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .grader-requirements.txt
      - name: Grade Assignment 01
        working-directory: assignments/a01/code/
        run: python grader.py
